### ISSUE TITLE
On lun add/remove all iscsi sessions are restarting

### ISSUE THREAD

**Issue by redtex** [sahlberg/libiscsi#153]
Hi, I'm using scst v3.0.2 target with Proxmox VE 3.4, libiscsi 1.12

When I add/remove iscsi LUN, whole VM's which connected to this
target stops it's disk activity, and seems to be forced to re-connect to
target. It's not a problem when you have 3-5 luns, but when target have
more than 100 luns this re-connect sequence takes about 10 minutes Is
it possible, to change such behavior ? 

SCST team's answer on such request follows:

Please ask the Proxmox maintainers to modify how SCSI unit attention conditions are handled in Proxmox. SCST submits a "REPORTED LUNS DATA HAS CHANGED" to the initiator after a LUN has been added or removed. If the initiator receives that UA it should rescan LUNs instead of disconnecting and reconnecting. See also http://www.t10.org/lists/asc-num.htm for a complete list of unit attention conditions. 

And Proxmox anwer is:
I think someone should post the problem on the libiscsi list.

So, here I am.

**Comment by sahlberg** [comment]
Hi,


On Wed, Apr 8, 2015 at 4:48 AM, redtex <notifications@github.com> wrote:

> Hi, I'm using scst v3.0.2 target with Proxmox VE 3.4, libiscsi 1.12
>
> When I add/remove iscsi LUN, whole VM's which connected to this
> target stops it's disk activity, and seems to be forced to re-connect to
> target. It's not a problem when you have 3-5 luns, but when target have
> more than 100 luns this re-connect sequence takes about 10 minutes Is
> it possible, to change such behavior ?
>
> SCST team's answer on such request follows:
>
> Please ask the Proxmox maintainers to modify how SCSI unit attention
> conditions are handled in Proxmox. SCST submits a "REPORTED LUNS DATA HAS
> CHANGED" to the initiator after a LUN has been added or removed. If the
> initiator receives that UA it should rescan LUNs instead of disconnecting
> and reconnecting. See also http://www.t10.org/lists/asc-num.htm for a
> complete list of unit attention conditions.
>
> And Proxmox anwer is:
> I think someone should post the problem on the libiscsi list.
>

I don't think libiscsi is resetting the connections here. On a connected
session and the application uses the async interface libiscsi will not
parse the emaning of the sense codes but instead just pass them back to the
application to deal with.


https://github.com/sahlberg/libiscsi/blob/master/lib/iscsi-command.c#L436

So, if a task is responded to by CHECK_CONDITION/UNIT_ATTENTION libiscsi
will just pass this back to application to parse and decide how to handle.
In that case the application can inspect
  task->sense.key and task->sense.ascq
to decide what to do.


I do not know how Proxmos worksbut it sounds to me that what you want to do
here is to have Poromix to parse the task->sense structure on check
condition and have it not trigger a
iscsi_reconnect() on this kind of sense code.
I.e. teach it about sense codes and have it not call iscsi_reconnect() for
those sense codes that do not need it.

Guessing on Poromox internals,  for this case I guess maybe you want to do
something like this when this sense code is returned:
* issue a iscsi_report_luns_task to re-read the set of LUNs.
  then remove any sessions that reflect to luns that no longer exist and
  create new sessions to new luns that have appeared
  but leave all sessions as is for luns that are unchanged.
* maybe issue a iscsi_readcapacity16_task to the LUN to see if it has
changed size if you track this internally inside Poromox and need to update
the metadata
* and finally reissue the iscsi_*_task command that you originally sent
that then ended with a unit attention check condition.

That is probably what it needs to do instead of re-cycling all sessions.




We are about to add a feature to make the reconnect async, so that it will
have less impact on applications. That will come in the next few weeks but
that may only make the reconnect have a little less impact on the
application.
The main thing to do is likely to make sure that you don't trigger a
reconnect in the first place and that likely involves changing how Poromox
handles when a task is failed with a check condition.



I might have misunderstood something, so please if you can provide more
exact details of the actual events that trigger this.

**Comment by sahlberg** [comment]
You use QEMU, right?

During normal operations, as in not during initial connect,  libiscsi does
not act on sense codes. Instead it just passes any sense codes it receives
back to the application.
The application then can if the status is CHECK_CONDITION inspect the
actual sense codes that is returned in the task->sense structure
and then upon what the sense codes are decide how to proceed.


In QEMU there is one dedicated iscsi context and session for each LUN so if
the set of LUNs exposed from the target changes, this would require
removing sessions for deleted LUNs and creating brand new sessions for
newly created LUNs. This would then need to be communicated to the guest OS
too so it would learn about these changes.
I don't think any of that exists in QEMU yet.
That is for exposing LUN changes to the guest.


If you do not care about the case when LUNs might have been added/removed
and don;t care about exposing this to the guest things are simpler.
By looking in recent qemu sources :
http://git.qemu.org/?p=qemu.git;a=blob;f=block/iscsi.c;h=3e34b1f3a240493a823a545fc455bd64f32ea975;hb=5a24f20a7208a58fb80d78ca0521bba6f4d7b145#l178

qemu already does check for UNIT_ATTENTION and treats it just as a NO-OP
and re-tries the failed command.


So if you use a current version of QEMU, it looks like it already does
check for UNIT_ATTENTION,
prints a log message :
179
<http://git.qemu.org/?p=qemu.git;a=blob;f=block/iscsi.c;h=3e34b1f3a240493a823a545fc455bd64f32ea975;hb=5a24f20a7208a58fb80d78ca0521bba6f4d7b145#l179>
                error_report("iSCSI CheckCondition: %s",
180
<http://git.qemu.org/?p=qemu.git;a=blob;f=block/iscsi.c;h=3e34b1f3a240493a823a545fc455bd64f32ea975;hb=5a24f20a7208a58fb80d78ca0521bba6f4d7b145#l180>
                             iscsi_get_error(iscsi));
and then just retries the SCSI task.


This should not trigger a full reconnect of the session.

**Comment by plieven** [comment]
Can you check the qemu and libiscsi version is used in Proxmox?

Originally the iscsi driver of Qemu did not handle UNIT ATTENTTION check conditions
correctly, but this was fixed I think at least 2 years ago.

As you say you get a UNIT_ATTENTION if you add or remove a LUN am I right that
you have all your targets unter the same iqn and just have different LUN IDs?
I think e.g. NetApp provides iSCSI this way. The whole filer has one target and each
volume is a LUN. Which makes it almost impossible to use it with open-iscsi, btw.

If Qemu or libiscsi initiates a reconnect there must have been an error or a timeout.
A UNIT_ATTENTION in old Qemu can only bring an I/O error in the guest no reconnect.

Is it possbible to specifiy environment variables in Proxmox and redirect the output
of the hypervisor to a file or syslog? If possible please specify environment variable
LIBISCSI_DEBUG=2 and provide the output around the time when the reconnect happens.

My guess is that there is sth wront if the LUN ID is not 0. One thing I have in mind is
that we do not use the right LUN ID for a NOP-Out as a reply to a target initiated NOP-In.
We always set 0 there and not what was provided by the garget.
In this case the target would issue a Protocol Error which would cause a reconnect.

Peter

**Comment by redtex** [comment]
Hi !!
Currently, we are using libiscsi 1.12 and qemu 2.1.3
You have right understanding of our's setup - one target with many luns.
with LIBISCSI_DEBUG=2 I have this on VM start, and no more, even on reconnect:

libiscsi:2 connecting to portal 192.168.107.23 [iqn.2005-05.com.sdsys1:pool2t]
libiscsi:2 connection established (192.168.107.4:40592 -> 192.168.107.23) [iqn.2005-05.com.sdsys1:pool2t]
libiscsi:2 login successful [iqn.2005-05.com.sdsys1:pool2t]
libiscsi:1 SENSE KEY:UNIT_ATTENTION(6) ASCQ:BUS_RESET(0x2900) [iqn.2005-05.com.sdsys1:pool2t]

so, what you can me to advise to do ???

p.s. with LIO there is no such issue, but I want to stay with SCST

**Comment by plieven** [comment]
Am 09.04.2015 um 13:49 schrieb redtex:
>
> Hi !!
> Currently, we are using libiscsi 1.12 and qemu 2.1.3
>
That should definetly have relevant patches.

> You have right understanding of our's setup - one target with many luns.
> with LIBISCSI_DEBUG=2 I have this on VM start, and no more, even on reconnect:
>
> libiscsi:2 connecting to portal 192.168.107.23 [iqn.2005-05.com.sdsys1:pool2t]
> libiscsi:2 connection established (192.168.107.4:40592 -> 192.168.107.23) [iqn.2005-05.com.sdsys1:pool2t]
> libiscsi:2 login successful [iqn.2005-05.com.sdsys1:pool2t]
> libiscsi:1 SENSE KEY:UNIT_ATTENTION(6) ASCQ:BUS_RESET(0x2900) [iqn.2005-05.com.sdsys1:pool2t]
>

But your vServer is wokring up to the reconnect?

If you reconnect there should be log output stating that a reconnect is initiated.

Can you verify please.


> so, what you can me to advise to do ???
>
> p.s. with LIO there is no such issue, but I want to stay with SCST
>

Okay, I currently don't have time to install SCST and test myself.

Ronnie, do you have time?

Peter

**Comment by redtex** [comment]
Hi !!!
I think, that it is reconnect, because if i disable new connections on SCST side:
echo 0 > /sys/kernel/scst_tgt/targets/iscsi/iqn...../enabled
VMs hangs forever after lun add or remove.

**Comment by sahlberg** [comment]
Can you take a network trace when the disconnect/reconnect happens ?

**Comment by redtex** [comment]
Yes, I've made it by tcpdump on hypervisor.
It's network activity between hypervisor and target.
Iv'e attached renamed 7z arcive to jpg  - without rename, I can't attach a file to this message.

![dump 7z](https://cloud.githubusercontent.com/assets/8180104/7070700/406e5296-dee9-11e4-8974-90fe4af8e858.jpg)

**Comment by redtex** [comment]
Now I've done the same, but qemu run with lun imported to hypervisor by open-iscsi.
The problem not appeared - so, it's definitely somewhere in libiscsi.

**Comment by sahlberg** [comment]
Ah,   SCST sends an AsyncMessage. We don't handle these and these trigger a
reconnect.

Since we can not pass them back up through to the application, since there
is not real api for that,  we could just silently ignore any of these.

**Comment by sahlberg** [comment]
I will create a change to libiscsi that will just silently eat and ignore
all AsyncMessages of type 0. That should remove the reconnects for this
case.
Currently these are handled internally as unrecognized/invalid PDUs.

I will upload it later tonight so you can test.
Thanks!

**Comment by redtex** [comment]
I'll be waiting :)
Thank you !

**Comment by sahlberg** [comment]
Please try current master branch for libiscsi. It should now just silently
ignore any/all such messages we get from the target.

**Comment by redtex** [comment]
Thank you very much for quick resolution.
Your's patch work as expected, but I had to apply it to tag 1.13.0, because in master you have bug - it connects to lun 0 only, no matter what passed with command line.

**Comment by sahlberg** [comment]
Another thing that looks suboptimal here is how your application is writing
data.

For example packets 49-69
Here your application is writing 6 4kb pages, once at a time.

Then in packets 78-83  it performs SYNCHRONIZE CACHE, once for each write,
but it also specifies in each of them lba==xferlen==0 which means flush all
data on the device.


This will likely hurt performance since it requires two roundtrips for each
write.
This could be to just a single roundtrip per write if your guest/app set
the DPO/FUA  flags in each SCSI WRITE command it generates.


I.e. you will get better performance if you change your app from doing
writes like this,as you currently do :

   WRITE one 4kb block with DPO==0 FUA==0
   SYNCHRONIZE CACHE for the whole device (potentially very expensive)

to instead do

  WRITE one 4kb block with DPO==1 FUA==1

**Comment by plieven** [comment]
Hi Ronnie, this is Qemus way to do it if the cache is not writeback. If I understand correctly you propose the following:

a) cache = writethrough, directsync, none etc.:

WRITE with FUA==1, DPO==1
make the flush call in Qemu a NOOP.

b) cache = writeback

WRITE with FUA==0, DPO==0
leave the flush as is.

In writeback mode Flushes are only send at certain points. The ability to pass flushes from the Guest to the Storage is negotiaged at least when using Virtio.

Peter

**Comment by redtex** [comment]
Hi !!
Well, to be clear, what I have done for this test:
qemu with virtio cache=directsync,
inside vm (Centos 6) I run:
for i in {1..1000}; do echo "meme" > meme; sync; rm -f meme; sync; sleep 1; echo $i; done

**Comment by sahlberg** [comment]
On Mon, Apr 13, 2015 at 11:41 PM, plieven <notifications@github.com> wrote:

> Hi Ronnie, this is Qemus way to do it if the cache is not writeback. If I
> understand correctly you propose the following:
>
> a) cache = writethrough, directsync, none etc.:
>
> WRITE with FUA==1, DPO==1
> make the flush call in Qemu a NOOP.
>
> b) cache = writeback
>
> WRITE with FUA==0, DPO==0
> leave the flush as is.
>
> In writeback mode Flushes are only send at certain points. The ability to
> pass flushes from the Guest to the Storage is negotiaged at least when
> using Virtio.
>
> Peter
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sahlberg/libiscsi/issues/153#issuecomment-92649623>.
>

Yes.   A bit off-topic for this thread  but it should have a noticeable
impact on latency I think.
The device specific bit in the ModeSense reply has a flag that signals
whether the device supports DPO/FUA or not so it should probably check that
bit first, but I think virtually all devices support this.
