### ISSUE TITLE
iscsi-test-cu can't cope with abort?

### ISSUE THREAD

**Issue by sitsofe** [sahlberg/libiscsi#185]
While running ```iscsi-test-cu``` with ```-t ALL``` against a software iSCSI target libiscsi failed to respond to a NOP making the initiator abort the connection. libiscsi went on to establish a new connection but became stuck in ```iscsi_logout_sync```.

**Comment by sahlberg** [comment]
I will try to reproduce this.
I guess hacking TGTD to not respond to NOP should be sufficient.

Do you by any chance know which particular test it hangs for and do you
have a network trace ?

**Comment by sahlberg** [comment]
Since the test tool does not initiate NOP I assume you mean that
* the target sends NOP to libiscsi
* libiscsi failed to respond to the NOP
* eventually the target drops the connection and libiscsi fails to recover
?

I tried but failed to reproduce by :
* setting up a target that sends NOPs and will drop the connection on failure
* deliberately break the NOP processing/responding in libiscsi

When I run the tests the target does drop the connection when libiscsi does not respond
but libiscsi successfully always reconnect successfully.


Can you send me a network trace when this triggers?

**Comment by sitsofe** [comment]
My understanding is that yes, it's the target sending the NOP. Please find a tcpdump on http://sucs.org/~sits/test/libiscsi/iscsi.pcap.xz . Test that generated the problem was run like so:
```
iscsi-test-cu -V -d -n -t ALL iscsi://10.1.3.243/cached1/0  iscsi://10.1.4.132/cached1/0
```
The last thing seen from the test is the following:
```
    Send READ16 (Expecting SUCCESS) LBA:2096897 blocks:255 rdprotect:0 dpo:0 fua:0 fua_nv:0 group:0
    [OK] READ16 returned SUCCESS NO SENSE(0x00) (null)(0x0000)

    Test COMPAREANDWRITE DPO/FUA flags
    Read the DPOFUA flag from mode sense data
    Send MODESENSE6 (Expecting SUCCESS) 
    [OK] MODESENSE6 returned SUCCESS NO SENSE(0x00) (null)(0x0000)
    [SUCCESS] Mode sense returned status GOOD
    Read the first block
    Send READ10 (Expecting SUCCESS) LBA:0 blocks:1 rdprotect:0 dpo:0 fua:0 fua_nv:0 group:0
    [OK] READ10 returned SUCCESS NO SENSE(0x00) (null)(0x0000)
    DPOFUA flag is set. Device should allow DPO/FUA flags in CDBs
    Test COMPAREANDWRITE with DPO==1
    Send COMPAREANDWRITE (Expecting SUCCESS) LBA:0 LEN:1024 WRPROTECT:0
    [OK] COMPAREANDWRITE returned SUCCESS NO SENSE(0x00) (null)(0x0000)
    Test COMPAREANDWRITE with FUA==1
    Send COMPAREANDWRITE (Expecting SUCCESS) LBA:0 LEN:1024 WRPROTECT:0
    [OK] COMPAREANDWRITE returned SUCCESS NO SENSE(0x00) (null)(0x0000)
    Test COMPAREANDWRITE with DPO==1 FUA==1
    Send COMPAREANDWRITE (Expecting SUCCESS) LBA:0 LEN:1024 WRPROTECT:0
    [OK] COMPAREANDWRITE returned SUCCESS NO SENSE(0x00) (null)(0x0000)
    Try fetching REPORT_SUPPORTED_OPCODES for COMPAREANDWRITE
    Send REPORT_SUPPORTED_OPCODE (Expecting SUCCESS) RCTD:0 OPTIONS:1 OPCODE:0x89 SA:0 ALLOC_LEN:65535
    [SKIPPED] REPORT_SUPPORTED_OPCODES is not implemented.
    REPORT_SUPPORTED_OPCODES not implemented. Skipping this part of the test
```

until the test was killed with Ctrl-C.

**Comment by sitsofe** [comment]
Looking at the previous trace in wireshark shows a NOP around packet 32203
```
32203	11.020888	10.1.4.132	10.1.3.5	iSCSI	114	NOP In
```
This leads to a ```FIN``` and three seconds later libiscsi tries to log out which results in a ```RST```.

**Comment by sahlberg** [comment]
Ok, I have reproduced by hacking up tgtd.
Should be fixed now.


The root cause is that iscsi-test-cu uses the simplistic synchronous api.
This is a nice API for trivial applications to use since it is so simple
and since it does not require that you set up
an even system to plug libiscsi into.
(Real applications instead use the asynchronous interface but it is a bit
of work to rewrite iscsi-test-cu to do this right now. I may do that later.)

In the synchronous API we only have an event loop running only when we have
a synchronous command in flight and then only for that particular context.
The problem in iscsi-test-cu is that when using multipathing, we create
multiple sessions but we almost never send commands down the secondary
paths.
That means we never invoke any event loops for the secondary paths and thus
IF the target uses NOPs, we will never respond to them and the target will
tear
down the connection.

A fix for that is added in
https://github.com/sahlberg/libiscsi/commit/5532325042e37e44bbb5419ce42c35af776a58d5
where iscsi-test-cu now tries to check for events and process them for the
secondary paths once every ~2 seconds.

That will allow us to respond semi-quickly to NOPs on these sessions.


The second fix is in libiscsi itself :
https://github.com/sahlberg/libiscsi/commit/0407cf6aed5e7acf0d99afaa9ce5d5179a8986cc
IF we have a session failure while the synchronous iscsi_logout_sync() is
in flight, then fail the command with an error instead of just discarding
the PDU.

**Comment by sitsofe** [comment]
Thanks Ronnie - those commits seem to have solved the problem.
