### ISSUE TITLE
[RFE] fuse-iscsi

### ISSUE THREAD

**Issue by jirib** [sahlberg/libiscsi#238]
Hello,

it would be great if there would be a fuse-iscsi via libiscsi. At least OS X users could benefit an open-source way to access iSCSI storage.

It could be beneficial for OpenBSD users where iSCSI initiator is still under development.

**Comment by sitsofe** [comment]
It wouldn't be FUSE you would need to support because iSCSI serves up block devices and not  filesystems. You would need OpenBSD to support block devices that came from userspace input ala NBD on Linux.

At any rate it wouldn't be libiscsi that would need to implement it but rather some 3rd-party project or OpenBSD itself...

**Comment by sitsofe** [comment]
(PS: Isn't there an open source kernel based OSX initiator over on https://github.com/iscsi-osx/iSCSIInitiator ?)

**Comment by jirib** [comment]
LOL, I had to have some short-cut. Yes, iSCSI is not file-based :) Thus closing this bug.
