### ISSUE TITLE
[openbsd] Can't get lun from EMC VNX from an OpenBSD box

### ISSUE THREAD

**Issue by jirib** [sahlberg/libiscsi#239]
Hi,

I have a strange issue, I can't list iscsi luns from an EMC VNX box from OpenBSD but I can do it from an EL7 box (although with a little bit older version). I see there's difference in next iSCSI packet following 'Login Response', see how 'Key/Value Pairs' is "cut" on OpenBSD (and this is last caught packet from the communication):

First EL7 box libiscsi-utils-1.9.0-7.el7.x86_64:

```
$ tshark -r /tmp/dumpY -O iscsi  frame.number==9 | sed -n '/^iSCSI/,$p'
iSCSI (Text Command)
    Opcode: Text Command (0x04)
    .1.. .... = I: Immediate delivery
    Flags: 0x80
        1... .... = F: Final PDU in sequence
        .0.. .... = C: Text is complete
    TotalAHSLength: 0x00
    DataSegmentLength: 16 (0x00000010)
    LUN
        00.. .... = Address Mode: Simple logical unit addressing (0x00)
        ..00 0000  0000 0000 = LUN: 0x0000
    InitiatorTaskTag: 0x00000001
    TargetTransferTag: 0xffffffff
    CmdSN: 0x00000000
    ExpStatSN: 0x00000000
    HeaderDigest: 0xa1ffc62b (Good CRC32)
    Key/Value Pairs
        KeyValue: SendTargets=All
```
And OpenBSD 6.0-current libiscsi-1.15.0p0:

```
$ tshark -r /tmp/dumpX -O iscsi  frame.number==7 | sed -n '/^iSCSI/,$p'
iSCSI (Login Response)
    Opcode: Login Response (0x23)
    1... .... = T: Transit to next login stage
    .0.. .... = C: Text is complete
    .... 01.. = CSG: Operational negotiation (0x1)
    .... ..11 = NSG: Full feature phase (0x3)
    VersionMax: 0x00
    VersionActive: 0x00
    TotalAHSLength: 0x00
    DataSegmentLength: 388 (0x00000184)
    ISID: 802d21e10000
        10.. .... = ISID_t: Random (0x2)
        ..00 0000 = ISID_a: 0x00
        ISID_b: 0x2d21
        ISID_c: 0xe1
        ISID_d: 0x0000
    TSIH: 0x0050
    InitiatorTaskTag: 0x763b5499
    StatSN: 0x00000000
    ExpCmdSN: 0x00796af7
    MaxCmdSN: 0x00796b15
    Status: Success (0x0000)
    Key/Value Pairs
```
Any idea?

**Comment by jirib** [comment]
https://gist.github.com/jirib/1ec1edb87a37e7d50c03fdbcc8622662

**Comment by jirib** [comment]
Same issue with 1.18.0 :(

**Comment by jirib** [comment]
there's something wrong where, when using 10.34.63.200 it says 'can't resolve'...

```
jirib:/home/jirib/openbsd/pobj/libiscsi-1.18.0/fake-amd64/usr/local
$ env LD_LIBRARY_PATH=./lib ktrace -id -f /tmp/kdump ./bin/iscsi-ls -d -i iqn.1994-05.com.redhat:f1a95ad9a787 -s iscsi://10.34.63.200
libiscsi:1 Invalid target:  Can not resolv into IPv4/v6.
libiscsi:1 reconnect try 1 failed, waiting 1 seconds
^C

jirib:/home/jirib/openbsd/pobj/libiscsi-1.18.0/fake-amd64/usr/local
$ env LD_LIBRARY_PATH=./lib ktrace -id -f /tmp/kdump ./bin/iscsi-ls -d -i iqn.1994-05.com.redhat:f1a95ad9a787 -s iscsi://10.34.63.202
Target:iqn.2016-11.com.redhat.brq.eng.lab.rhev:str-01:sdciscsipool.jbelka Portal:10.34.63.202:3260,1
iscsi_connect failed. Failed to log in to target. Status: Authorization failure(514)
```

ktrace dump https://gist.github.com/jirib/a568900e0ec42bbfb004056557e7e0fa

**Comment by sahlberg** [comment]
The reply from your iscsi target has the key/values cut because the server
has split the iscsi header and the key/value payload into two separate tcp
segments.
That is fairly normal and you can workaround that by enabling "TCP
reassembly" in wireshark/tshark.

**Comment by sahlberg** [comment]
jirib:/home/jirib/openbsd/pobj/libiscsi-1.18.0/fake-amd64/usr/local
$ env LD_LIBRARY_PATH=./lib ktrace -id -f /tmp/kdump ./bin/iscsi-ls -d -i
iqn.1994-05.com.redhat:f1a95ad9a787 -s iscsi://10.34.63.202
Target:iqn.2016-11.com.redhat.brq.eng.lab.rhev:str-01:sdciscsipool.jbelka
Portal:10.34.63.202:3260,1
iscsi_connect failed. Failed to log in to target. Status: Authorization
failure(514)

This looks like an ACL issue rather than an iscsi protocol issue.

Authorization failure means that the target is configured to not allow the
initiator to connect.


Update your target configuration and make it allow
 iqn.1994-05.com.redhat:f1a95ad9a787
to connect.
Alternatively you can probably disable access control completely on your
target.

**Comment by jirib** [comment]
Part with auth failure was there just for comparison.

**Comment by sahlberg** [comment]
Ok, please send me a full wireshark trace of when you are running the
iscsi-ls command.

**Comment by jirib** [comment]
https://www.afterboot.cz/pub/dump 

Sorry for delay.

**Comment by sahlberg** [comment]
I think the target might be slightly broken with regard to header digest.

During login negotiation iscsi-ls offers both CRC32C and None as settings
for HeaderDigest.
Your target picks CRC32C.   Then when iscsi-ls proceeds to send the text
message for discovery, iscsi-ls
uses header digest, since the target told it to,  and the target just
closes the session.


Now, header digest is very unusual that targets support for discovery
sessions.


I have changed iscsi-ls to not try to negotiate HeaderDigest CRC32C for its
discovery phase.

You may want to talk to the EMC folks and have them look into things.


If you write your own apps to talk to the target you may want to make sure
you add a
iscsi_set_header_digest(iscsi, ISCSI_HEADER_DIGEST_NONE);

anytime you try to negotiate a discovery sessions.

Try latest version of libiscsi. Its version of iscsi-ls has a workaround
for this issue.

**Comment by sahlberg** [comment]
At least that is what I think is wrong.


There is nothing wrong in what iscsi-ls does in your trace.
It logs in successfully, and sends a TextCommand for discovery.

The server then just simply tears down the connection without sending any
response.
Check the logs on your target and see if you can find anythong about WHY it
decided to just shut down.

The only thing unusual in your trace is the fact that your target tries to
negotiate crc32c for header digest for a discovery session.
That is the only thing unusual that stands out and what I would focus on.

**Comment by sahlberg** [comment]
A workaround for this bug is in current master.

The underlying bug is that the target tries to negotiate CRC32C, if given the option, during the discovery phase.
As the target, like every target,  does not support header digest during discovery, it should not try to negotiate it.


Pass this trace to the emc folks and have them look into it.
They probably want to fix their target so that it does not select CRC32C for header digest during discovery as it is not supported.
